In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [4]:
v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])

In [7]:
v_add = v1 + v2
v_sub = v1 - v2
print (v_add, v_sub)

[ 3  7 11 15] [-1 -1 -1 -1]


In [9]:
magnitude = np.linalg.norm(v_add)
print(magnitude)

20.09975124224178


In [14]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[2, 4, 6], [7, 8, 9], [1, 2, 5]])
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [7 8 9]
 [1 2 5]]


In [17]:
A = np.array([[2, 1], [1, 2]])
e_value, e_vector = np.linalg.eig(A)
print(e_value)
print(e_vector)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [19]:
A = np.array([[4, 1], [6, 3]])
A_inverse = np.linalg.inv(A)
identity = np.dot(A, A_inverse)
print(identity)

[[1. 0.]
 [0. 1.]]
