# Gaussian Elimination/LU Decomposition

In [1]:
import numpy as np

In [48]:
def gaussian_elimination(A,b):
    n = len(b)
    for i in range(n):
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        
        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    
    # Backward substitution (solving the new matrix)
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [21]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)  # Initialize L as an identity matrix
    U = np.array(A, dtype=float)  # Copy of A to avoid
    # modifying the original matrix
        # modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            factor = U[j, i] / U[i, i]  # Multiplier for row
     # operation
            L[j, i] = factor  # Store multiplier in L
            
            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    
    return L, U

In [41]:
A = np.array([[10, 3, 2],[1, 5, 3],[9, 5, 2]])
b = np.array([5.0,2.0,9.0])

In [44]:
npans = np.linalg.solve(A, b)
myans = gaussian_elimination(A,b)
print(npans)
print(myans)
print(A)

[ 0.575  2.25  -3.75 ]
[0.575, 2.25, -3.75]
[[10  3  2]
 [ 0  4  2]
 [ 0  0 -1]]


In [45]:
A = np.array([[10, 3, 2],[1, 5, 3],[9, 5, 2]]) #reset matrix A because it is gaussian matrix form now
myansL, myansU = lu_decomposition(A)
print(myansL)
print(myansU)

[[1.        0.        0.       ]
 [0.1       1.        0.       ]
 [0.9       0.4893617 1.       ]]
[[10.          3.          2.        ]
 [ 0.          4.7         2.8       ]
 [ 0.          0.         -1.17021277]]


In [46]:
print(A)
print(myansL@myansU)

[[10  3  2]
 [ 1  5  3]
 [ 9  5  2]]
[[10.  3.  2.]
 [ 1.  5.  3.]
 [ 9.  5.  2.]]


In [47]:
#returns A again when I matrix multiply myansL and myansU